commmands
  # Hora
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: Me digas haras.
    entity: time
    actin: getTime
  # Data
  - command:
    input: Qual é a data de hoje
    entity: time
    action: getDate
  - command:
    input: Qual data de hoje
    entity: time
    action: getDate
  # Tempo
  - command:
    input: Previsão do tempo
    entity: weather
    action: getWeather
  - command:
    input: Como esta o clima?
    entity: weather
    action: getWeather
  # Open
  - command:
    input: Abrir google
    entity: open
    action:
  - command:
    input: Abra youtube
    entity: weather
    action: getWeather